# Generated by Django 3.0 on 2019-12-18 03:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('caseid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('doc', models.FileField(upload_to='reports/%Y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MappingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Protocols',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protocol_name', models.CharField(max_length=200, unique=True, verbose_name='Protocol Name')),
                ('short_cut', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=25)),
                ('amazon_number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speck_number', models.CharField(max_length=30, null=True, verbose_name='Speck Number')),
                ('regulation', models.TextField(verbose_name='Regulation')),
                ('requirement_title', models.TextField(verbose_name='Requirement title')),
                ('link', models.URLField()),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('test_method', models.TextField(verbose_name='Test Method')),
                ('requirement', models.TextField(verbose_name='Requirement')),
                ('protduct_scope', models.CharField(max_length=100, verbose_name='Product Scope')),
                ('exemption', models.CharField(default='NA', max_length=30)),
                ('protocol_section', models.CharField(max_length=100)),
                ('mandatory_voluntary', models.CharField(max_length=30)),
                ('is_cornerstone', models.BooleanField(default=False, verbose_name='Is Cornerstone')),
                ('new_voluntary_safety_standard', models.TextField(null=True, verbose_name='New Voluntary Safety Standard')),
                ('reationale', models.CharField(max_length=50, null=True, verbose_name='Reationale')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('protocol_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapsa.Protocols')),
            ],
        ),
        migrations.CreateModel(
            name='MiningQueue',
            fields=[
                ('sessionid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapsa.Document')),
            ],
        ),
        migrations.CreateModel(
            name='MiningLog',
            fields=[
                ('caseid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('stage1', models.CharField(choices=[('1', 'Processing'), ('2', 'Success'), ('3', 'Fail'), ('4', 'Stop')], max_length=3)),
                ('stage2', models.CharField(choices=[('1', 'Processing'), ('2', 'Success'), ('3', 'Fail'), ('4', 'Stop')], max_length=3)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('doc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dapsa.Document')),
            ],
        ),
        migrations.CreateModel(
            name='ConlusionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequence', models.IntegerField(default=0)),
                ('phased_requirement_title', models.CharField(max_length=200)),
                ('scenario', models.CharField(choices=[('1', 'Missing'), ('2', 'Pass'), ('3', 'Fail')], max_length=3)),
                ('page', models.IntegerField(default=0)),
                ('reasons', models.TextField()),
                ('comments', models.TextField()),
                ('caseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapsa.MiningLog')),
                ('protocol_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_section_r', to='dapsa.Protocol')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_r', to='dapsa.Protocol')),
                ('requirement_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_title_r', to='dapsa.Protocol')),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=50)),
                ('protocol', models.CharField(max_length=200)),
                ('extract_report_date', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=200)),
                ('factory', models.CharField(max_length=200)),
                ('caseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapsa.MiningLog')),
            ],
        ),
    ]
