# Generated by Django 3.0 on 2020-01-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='exemption',
            field=models.TextField(blank=True, default='NA'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='mandatory_voluntary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protduct_scope',
            field=models.TextField(blank=True, verbose_name='Product Scope'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='protocol_section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='region',
            field=models.TextField(blank=True, null=True, verbose_name='Region'),
        ),
    ]
