# Generated by Django 3.0 on 2019-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocols',
            name='amazon_number',
            field=models.IntegerField(),
        ),
    ]
