# Generated by Django 3.0 on 2020-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0002_auto_20200103_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='inner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
