# Generated by Django 3.0 on 2019-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0003_auto_20191220_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pl',
            field=models.CharField(blank=True, default='temp', max_length=255),
        ),
    ]
