# Generated by Django 3.0 on 2019-12-23 10:33

import dapsa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0004_auto_20191223_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(max_length=255, upload_to=dapsa.models.pl_dirtory_path),
        ),
    ]
