# Generated by Django 3.0 on 2020-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0004_auto_20200103_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='protduct_scope',
            field=models.TextField(blank=True, null=True, verbose_name='Product Scope'),
        ),
    ]
