# Generated by Django 3.0 on 2020-01-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0005_auto_20200103_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='speck_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Speck Number'),
        ),
    ]
