# Generated by Django 3.0 on 2020-01-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0006_auto_20200103_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='exemption',
            field=models.TextField(blank=True, default='NA', null=True),
        ),
    ]
