# Generated by Django 3.0 on 2020-01-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0009_samplepool_asin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asinassign',
            name='task_type',
            field=models.CharField(blank=True, choices=[('1', 'SPB'), ('2', 'HPB'), ('3', 'CPB')], max_length=25, null=True),
        ),
    ]
