# Generated by Django 3.0.2 on 2020-01-21 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0010_asinassign_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubbleInfo',
            fields=[
                ('asin', models.CharField(max_length=25)),
                ('mfp', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mfp_code', models.CharField(max_length=50, null=True)),
                ('approval_type', models.CharField(max_length=150, null=True)),
                ('life_cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('active_region', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_approved', models.DateField(default=datetime.date(1, 1, 1))),
                ('experiration_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('first_request_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('earliest_test_request_date', models.DateField(default=datetime.date(1, 1, 1))),
                ('po_approve', models.CharField(blank=True, max_length=25, null=True)),
                ('approver', models.CharField(max_length=50, null=True)),
                ('escalation_tt', models.CharField(blank=True, max_length=300, null=True)),
                ('compliance_note', models.TextField(blank=True, null=True)),
                ('pl_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_no', models.CharField(max_length=300, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
