# Generated by Django 3.0.2 on 2020-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapsa', '0011_hubbleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubbleinfo',
            name='regular_body',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
